config/routes.rb
Rails.application.routes.draw do    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root "articles#index"

  resources :articles do
    resources :comments
  end

  resources :users do
    resources :articles
  end

  # List of users
  get '/users', to: 'users#index', as: "users_list"

  resources :follows, only: [:create]

  # Destroy->Unfollow function
  post "unfollow", to: "follows#destroy", as: "user_unfollow"

end

app/models/application_record.rb
# Model class default aaplication
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/concerns/visible.rb
# Model for article and comment
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"

    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  
  # Include default devise modules. Others available are: :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  # Follow
  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower

  def follow(user)
    active_follows.create(followed_id: user.id)
  end

  def unfollow(selfuser, user)
    active_follows.find_by(follower_id: selfuser.id, followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# Articles manager class
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  http_basic_authenticate_with name: 'dhh', password: 'secret', except: %i[index show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find(@article.user_id)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
# Comments manager class
class CommentsController < ApplicationController
  before_action :authenticate_user!
  http_basic_authenticate_with name: 'dhh', password: 'secret', only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ActionController::Base
    before_action :authenticate_user!
    before_action :find_user, only: [:create]

    def create
        current_user.follow(@user)
        redirect_back fallback_location: root_path
    end

    def destroy
        follower = current_user
        followed = User.find(params[:followed_user_id])
        current_user.unfollow(follower,followed)
        redirect_back fallback_location: root_path
    end

    private
    
    def find_user
        @user = User.find(params[:user_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<fieldset>
  <div class="card" style="width:50%; padding: 10px">
    <%= form_with model: article do |form| %>
    <div class="">
      <label for="exampleInputEmail1" class="form-label mt-4"><%= form.label :title %></label>
      <%= form.text_field :title, class:'form-control'%>
      <% article.errors.full_messages_for(:title).each do |message| %>
      <small class="form-text text-danger"><%= message %></small>
    </div>
    <% end %>

    <div class="">
      <label for="exampleTextarea" class="form-label mt-4"><%= form.label :body %></label>
      <%= form.text_area :body, class:'form-control', rows:'3' %>
      <% article.errors.full_messages_for(:body).each do |message| %>
      <small class="form-text text-danger"><%= message %></small>
    </div>
    <% end %>

    <div class="" style="padding:5px">
      <label for="exampleSelect1" class="form-label mt-4"><%= form.label :status %></label>
      <%= form.select :status, %w[public private archived], selected: 'public', class: 'form-select' %>
    </div>

    <div style="display: flex; justify-content: flex-end; width: 100%; padding: 5px">
      <div style="padding:5px">
        <%= form.submit class:'btn btn-outline-success' %>
      </div>
      <div style="padding:5px">
        <%= link_to 'Cancel', root_path(@article), :class => 'btn btn-outline-light' %>
      </div>
    </div>

    <% end %>
  </div>
</fieldset>

app/views/articles/edit.html.erb
<div style="padding: 10px">
    <h4>Edit Article</h4>
    <%= render 'form', article: @article %>
</div>

app/views/articles/index.html.erb
<div class="row" style="padding:15px">
  <% @articles.each_with_index do |article, i| %>
  <div class="card border-info mb-3 col-4" style="max-width: 20rem; margin: 10px">
    <div class="card-header">Article <%= i+1 %></div>
    <div class="card" style="width:25%;">
      <% if article.status == 'public' %>
        <span class="badge rounded-pill btn-secundary"><%= article.status %></span>
      <% elsif article.status == 'private' %>
        <span class="badge rounded-pill btn-primary"><%= article.status %></span>
      <% elsif article.status == 'archived' %>
        <span class="badge rounded-pill btn-warning"><%= article.status %></span>
      <% else %>
        <span class="badge rounded-pill btn-danger"><%= article.status %></span>
      <% end %>
    </div>
    <div class="card-body">
      <h4 class="card-title"><%= link_to article.title, article %></h4>
      <p class="card-text"><%= article.body %></p>
    </div>
  </div>
  <% end %>
</div>

<button class="btn btn-outline-primary"
        style="position:absolute; top:0; right:0; padding: 10px; margin:10px;"
        onclick="location.href='<%= new_article_path %>'">
          New Article
</button>

<div style="width:100%; display: flex; justify-content: flex-end; position:absolute; bottom:0; right:0; padding: 10px">
  <div class="card" style="width:20%;">
    <span class="badge bg-info">This blog has <%= Article.public_count %> public articles.</span>
    <span class="badge bg-dark">This blog has <%= @articles.size %> articles.</span>
  </div>
</div>

<div>
  <button class="btn btn-outline-info" style="padding: 10px; margin:10px;"
        onclick="location.href='<%= users_list_path %>'">
          Users
  </button>
</div>

app/views/articles/new.html.erb
<div style="padding: 10px">
    <h4>New Article</h4>

    <%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<div>
  <h1><%= @article.title %></h1>
  <p><%= @article.body %></p>
  <div style="padding 5px; display: flex; width: 100%; margin:5px">
    <% if user_signed_in? %>
      <% if @article.user_id == current_user.id %>
        <div style="margin-right:15px;"><%= link_to 'Edit', edit_article_path(@article), :class=>"btn btn-warning" %></div>
        <div style="margin-right:15px;"><%= button_to 'Delete article', article_path(@article),
                                                    method: :delete,
                                                    data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></div>
      <% end %>
    <% end %>
    <div style="margin-right:15px;"><%= link_to 'Home', root_path(@article), :class=>"btn btn-dark" %></div>
  </div>
</div>

<hr class="border-light" style="width:100%; height:2px;">

<div style="width:50%; padding: 10px; position:absolute; right:0;">
  <h2>Comments</h2>
  <%= render @article.comments %>
</div>

<% if user_signed_in? %>
  <% if current_user.following?(@user) || current_user==@user %>
    <div style="width:50%; padding: 10px; margin: 10px; bottom:0; left:0;">
      <h2>Add a comment:</h2>
      <p><%= render 'comments/form' %></p>
    </div>
  <% else %>
    <div style="width:50%; padding: 10px; margin: 10px; bottom:0; left:0;">
      <h4>To comment on this article, first follow its author<h4>
    </div>
  <% end %>
<% else %>
  <div style="width:50%; padding: 10px; margin: 10px; bottom:0; left:0;">
    <h4>To comment on this article, first sign in<h4>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<% case comment.status %>
  <% when "public" %>
  <div class='card border-secundary' style='padding:10px'>
  <% when "private" %>
  <div class='card border-primary' style='padding:10px'>
  <% when "archived" %>
  <div class='card border-warning' style='padding:10px'>
  <% else %>
  <div class='card border-danger' style='padding:10px'>
<% end  %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <!-- Delete Comm-->
  <div style="margin:5px">
    <% if user_signed_in? %>
    <div class="col"><%= button_to 'Delete comment', [comment.article, comment],
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></div>
    <% end %>
  </div>
  <!-- Delete Comm-->
</div>

app/views/comments/_form.html.erb
<fieldset>
  <% if user_signed_in? %>
  <div class="card" style="padding:10px">
    <%= form_with model: [@article, @article.comments.build] do |form| %>
    <div class="">
      <label for="exampleInputEmail1" class="form-label mt-4"><%= form.label :commenter %></label>
      <%= form.text_field :commenter, class:'form-control'%>
    </div>

    <div class="">
      <label for="exampleTextarea" class="form-label mt-4"><%= form.label :body %></label>
      <%= form.text_area :body, class:'form-control', rows:'3' %>
    </div>

    <div class="" style="padding:5px">
      <label for="exampleSelect1" class="form-label mt-4"><%= form.label :status %></label>
      <%= form.select :status, %w[public private archived], selected: 'public', class: 'form-select' %>
    </div>

    <div style="display: flex; justify-content: flex-end; width: 100%; padding: 5px">
      <div style="padding:5px">
        <%= form.submit class:'btn btn-outline-success' %>
      </div>
    </div>
    <% end %>
  </div>
  <% else %>
    <h4>Log in to comment.</h4>
  <% end %>
</fieldset>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Article-nation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-5">
            <a class="navbar-brand" href="<%= root_path(@article)%>">Articles Blog</a>
        </div>
    </nav>
    <div style="padding:10px">
      <div class="border-success" style="width:100%; display: flex; justify-content: flex-end;">
        <% if user_signed_in? %>
          <p class="text-muted" style="margin:10px"> Logged in as <strong><%= current_user.email %></strong> <p>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-outline-warning', :style => 'margin:5px' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-outline-danger', :style => 'margin:5px' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-outline-primary', :style => 'margin:5px'%> 
          <%= link_to "Login", new_user_session_path, :class => 'btn btn-outline-success', :style => 'margin:5px'%>
        <% end %>
      </div>
    </div>

    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div style="padding:10px"><%= yield %></div>
  </body>
</html>

app/views/list/index.html.erb
<div style="padding:5px;">
    <h3>List of users </h3>
    <% if user_signed_in? %>
    <% @user.each do |u| %>
        <% if u.id != current_user.id %>
        <div class="card bg-primary" style="width:25%; margin:10px; padding:10px">
            <p class="card-title"><strong>User: </strong><small class="text-secundary"><%= u.email %></small></p>
            <% if !current_user.following?(u) %>
                <%= button_to "Follow", follows_path(user_id: u.id), :class => 'btn btn-outline-light', :style => 'padding: 10px; margin:10px;'  %>
                </button>
            <% else %>
                <%= form_tag user_unfollow_path(u) do %>
                    <%= hidden_field_tag 'followed_user_id', u.id %>
                    <%= hidden_field_tag 'follower_user_id', current_user.id %>
                    <%= submit_tag "Unfollow", :confirm => 'Are you sure?', class: "btn btn-outline-danger", :style => 'padding: 10px; margin:10px;' %>
                <% end %>
                <%#= link_to "Unfollow", follows_path(), method: :delete%>
            <% end %>
        </div>
        <% end %>
    <% end %>
    <% end %>
</div>

app/views/users/index.html.erb
<div style="padding:5px;">
    <h3>List of users </h3>
    <% if user_signed_in? %>
    <% @user.each do |u| %>
        <% if u.id != current_user.id %>
        <div class="card bg-primary" style="width:25%; margin:10px; padding:10px">
            <p class="card-title"><strong>User: </strong><small class="text-secundary"><%= u.email %></small></p>
            <% if !current_user.following?(u) %>
                <%= button_to "Follow", follows_path(user_id: u.id), :class => 'btn btn-outline-light', :style => 'padding: 10px; margin:10px;'  %>
                </button>
            <% else %>
                <%= form_tag user_unfollow_path(u) do %>
                    <%= hidden_field_tag 'followed_user_id', u.id %>
                    <%= hidden_field_tag 'follower_user_id', current_user.id %>
                    <%= submit_tag "Unfollow", :confirm => 'Are you sure?', class: "btn btn-outline-danger", :style => 'padding: 10px; margin:10px;' %>
                <% end %>
            <% end %>
        </div>
        <% end %>
    <% end %>
    <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %><!-- Alert error forms -->
  <div id="error_explanation">
    <div class="alert alert-dismissible alert-danger">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      <strong><%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase) %>
      </strong> 
      <p class="alert-link">
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </p>
    </div>

  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>